---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: textparse-service
spec:
   selector:
      matchLabels:
         app: textparse-service
   replicas: 1
   template:
      metadata:
         labels:
            app: textparse-service
      spec:
         imagePullSecrets:
         - name: mysecret
         containers:
         - name: textparse-service
           image: chrissiddall.azurecr.io/ncreactportfoliotextparseservice:latest
           imagePullPolicy: Always
           resources:
           ports:
           - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
   name: textparse-service
spec:
   selector:
      app: textparse-service
   type: LoadBalancer
   ports:
      - port: 80
...